# Generated by Django 4.1.7 on 2023-03-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_task_user_alter_task_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
