# Generated by Django 4.1.7 on 2023-03-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
